version: 2
jobs:
  build:
    working_directory: ~/repo
    machine: true
    steps:
    - checkout
    - run: ls -l
    - run:
        name: docker-login
        command: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
    - run:
        name: build-docker-image
        command: docker build -t frix0docker/tp-devops .
    - run:
        name: push-docker-image
        command: docker push frix0docker/tp-devops