version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
    - image: circleci/node:10.16.3
    steps:
    - checkout
    - run:
        name: Install Docker client
        command: |
          set -x
          VER="17.03.0-ce"
          curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
          tar -xz -C /tmp -f /tmp/docker-$VER.tgz
          mv /tmp/docker/* /usr/bin
    - run:
        name: build-docker-image
        command: docker build -t khalilnouisser/metrics-api .
    - run:
        name: docker-login
        command: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
    - run:
        name: push-docker-image
        command: docker push khalilnouisser/metrics-api
    #- run:
    #    name: update-npm
    #    command: 'sudo npm install -g npm@5'
    #- restore_cache:
    #    key: dependency-cache-{{ checksum "package-lock.json" }}
    #- run:
    #    name: install-npm-wee
    #    command: npm install
    #- save_cache:
    #    key: dependency-cache-{{ checksum "package-lock.json" }}
    #    paths:
    #    - ./node_modules
    #- run:
    #    name: test
    #    command: npm test
    #- run:
    #    name: code-coverage
    #    command: './node_modules/.bin/nyc report --reporter=text-lcov'
    #- store_artifacts:
    #    path: test-results.xml
    #    prefix: tests
    #- store_artifacts:
    #    path: coverage
    #    prefix: coverage
    #- store_test_results:
    #    path: test-results.xml